### ISSUE TITLE
This project is excluded on the hacktoberfest 2022

### ISSUE THREAD

**Issue by AbbeyIT** [InvisiblePro/Hacktoberfest-2022#35]
**Describe the bug**
The project seems to have been excluded from the Hacktoberfest and won't be considered in your pull/merge request.

**Screenshots**
![image](https://user-images.githubusercontent.com/93916892/193465925-b02f5be8-4888-4611-9296-d8856b0fb389.png)

**Comment by InvisiblePro** [comment]
See! I havent reported any bug or spam or invalid label.
Still it is opened and I havent accepted

**Comment by InvisiblePro** [comment]
One idea could be applied!
You yourself close this PR and do it again!
It will be accepted

**Comment by InvisiblePro** [comment]
I really appreciate your programming skills in python!! 👏🏻

**Comment by InvisiblePro** [comment]
I would definitely like you to contribute in my Repo

Better option is that you close your existing PR and re-open it!

**Comment by AbbeyIT** [comment]
Thank you for your kind words to me. I appreciated it a lot. And how do you re-open a PR?

**Comment by InvisiblePro** [comment]
Close the pull request and create a new one

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.

**Comment by InvisiblePro** [comment]
@ItzLevvie , can you explain what is error with my repo?

**Comment by InvisiblePro** [comment]
Why it is showing "excluded"?

**Comment by InvisiblePro** [comment]
Is anything improper?

**Comment by Idhant-6** [comment]
Hi @ItzLevvie, I just wanted to ask, What laws have they violated so their repository is excluded from hacktoberfest? I mean, if there is something inappropriate, I think they should know that so that they don't repeat the same mistake again, Can you please ....?

**Comment by InvisiblePro** [comment]
Yea! On what basis they consider it as "excluded"?

**Comment by InvisiblePro** [comment]
Whether this is error of Maintainer or Contributor?

**Comment by ItzLevvie** [comment]
There is a commitment — which is a **_compulsary_** requirement — for contributors & maintainers to follow a set of guidelines which is listed [here](https://hacktoberfest.com/participation/).

This repository does not fall into the guidelines that were initially set by DigitalOcean. More specifically, this statement: "**_PR/MRs should be useful to maintainers. Repos that encourage simplistic PR/MRs (like adding a name or profile to a list or arbitrarily curating content) will be excluded from Hacktoberfest._**"

^ If you would like me to be even more specific - it's these 3 words: **_arbitrarily curating content_**

This repository was created for the sole purpose of allowing people to contribute pull requests (PRs) with no real purpose other than to be in the "minimum 4 pull requests (PRs)" window to be eligible for a T-Shirt from DigitalOcean.

This 1 week (7 days) of waiting time was implemented so that DigitalOcean can review more than 500K pull requests to ensure that each pull request (PR) meets the guidelines set. Lots of human moderators were chosen by DigitalOcean to take care of this.

If a particular repository was never reported to DigitalOcean where the sole purpose was to defeat the system - it's always — 50% to 75% — possible for your pull requests (PRs) to be flagged and have it **_not_** counted towards your contributions for Hacktoberfest 2022.

As always, humans are humans - and not robots. This means that it's sometimes possible for these pull requests (PRs) to slip through DigitalOcean's reviews and have your pull requests (PRs) counted towards your contributions for Hacktoberfest 2022.

Please be aware that if you made multiple repositories which were all excluded - it's better to be **_safe_** than sorry to say that it's always possible for DigitalOcean to blacklist your GitHub / GitLab account where any pull request (PR) made by other contributors to your repositories will not have their contributions counted towards Hacktoberfest 2022.

DigitalOcean is always looking to implement more safeguarding measures to prevent unfair unadvantage towards other people and every October in each year, those rules tend to expand.
